# Generated by Django 4.1.4 on 2022-12-21 16:40

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='modelo_Principal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('fecha_Modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('fecha_eliminacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('modelo_principal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Posteo_noti.modelo_principal')),
                ('nombre_autor', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidos_autor', models.CharField(max_length=120, verbose_name='Apellido')),
                ('email_auto', models.EmailField(max_length=200, verbose_name='Correo Electronico')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
            bases=('Posteo_noti.modelo_principal',),
        ),
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('modelo_principal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Posteo_noti.modelo_principal')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de categoria')),
                ('imagen', models.ImageField(upload_to='categoria/', verbose_name='imagen')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
            bases=('Posteo_noti.modelo_principal',),
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('modelo_principal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Posteo_noti.modelo_principal')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('correo', models.CharField(max_length=200, verbose_name='Correo Electronico')),
                ('asunto', models.CharField(max_length=100, verbose_name='Asunto')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
            bases=('Posteo_noti.modelo_principal',),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('modelo_principal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Posteo_noti.modelo_principal')),
                ('titulo_post', models.CharField(max_length=150, unique=True, verbose_name='Titulo del Post')),
                ('slug', models.CharField(max_length=150, unique=True, verbose_name='slug')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('contenido', ckeditor.fields.RichTextField()),
                ('imagen', models.ImageField(upload_to='categoria/', verbose_name='Imagen')),
                ('fecha_publicación', models.DateField(verbose_name='Fecha de publicacion')),
                ('autor_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Posteo_noti.autor')),
                ('categoria_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Posteo_noti.categoria')),
            ],
            bases=('Posteo_noti.modelo_principal',),
        ),
    ]
