# Generated by Django 4.1.4 on 2022-12-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Usuario', models.CharField(max_length=15)),
                ('Contraseña', models.CharField(max_length=20)),
                ('Tipo_Usuario', models.CharField(max_length=20)),
            ],
        ),
    ]
